#!/usr/bin/env bash
# iOS 版 libfushi_p2p.a（staticlib）+ 给 Runner 链接用的 xcconfig 片段。
#
# iOS 不允许 app 加载自带的任意 dylib，所以以静态库链进 Runner 主二进制，Dart 侧
# `DynamicLibrary.process()` 取符号（packages/fushi_p2p/lib/src/fushi_p2p_library.dart）。
# 链进去靠 fushi/ios/Flutter/{Debug,Release}.xcconfig 末尾的
#   #include? "../../../native/fushi_p2p/prebuilt/ios/fushi_p2p.xcconfig"
# 与 Runner 的 OTHER_LDFLAGS 里的 $(FUSHI_P2P_LDFLAGS)：
#   - 本脚本生成那份 xcconfig，定义 FUSHI_P2P_LDFLAGS = -force_load <.a> + Rust 要的系统库；
#   - 没跑过本脚本 → 可选 include 静默缺席 → 变量为空 → 不链接，P2P 能力判不可用，
#     Runner 照常构建（与 Windows/Android 的「prebuilt 有则随包」同一语义，Mac 上不装
#     Rust 也能出包）。
#   - 必须 -force_load：没有任何 Objective-C/Swift 代码引用 fp2p_*，普通链接会把整个
#     归档当无用成员丢掉；符号在 dead-strip 下靠 Runner 已有的 -Wl,-export_dynamic
#     与 STRIP_STYLE=non-global 保住（与 fushidicts 的 -force_load 同一套）。
#
# 用法: build_ios_staticlib.sh [device|simulator|all]   缺省 all
#   device    : aarch64-apple-ios                        → prebuilt/ios/iphoneos/libfushi_p2p.a
#   simulator : aarch64-apple-ios-sim + x86_64-apple-ios → prebuilt/ios/iphonesimulator/libfushi_p2p.a（lipo）
# 前提: rustup target add aarch64-apple-ios aarch64-apple-ios-sim x86_64-apple-ios
#
# 部署目标与 fushi/ios/Runner.xcodeproj 的 IPHONEOS_DEPLOYMENT_TARGET 对齐（15.1）。
set -euo pipefail

WHICH="${1:-all}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_DIR="$SCRIPT_DIR/prebuilt/ios"
export IPHONEOS_DEPLOYMENT_TARGET="${IPHONEOS_DEPLOYMENT_TARGET:-15.1}"

cd "$SCRIPT_DIR"

# 编一个 target 的 staticlib，把 rustc 报出的「链接方还需要的系统库」写到 $2。
# 静态库自己不带链接指令（framework 依赖在最终链接 Runner 时才解析），所以必须把
# `--print native-static-libs` 的结论交给 Xcode；先 clean 本 crate 保证这次真的会
# 重新编译并打印（依赖 crate 的缓存不受影响）。
build_target() {
  local target="$1" libs_out="$2"
  local log
  log="$(mktemp)"
  cargo clean --release --target "$target" -p fushi_p2p
  echo "==> cargo rustc --release --lib --target $target --crate-type staticlib (IPHONEOS_DEPLOYMENT_TARGET=$IPHONEOS_DEPLOYMENT_TARGET)"
  cargo rustc --release --lib --target "$target" --crate-type staticlib \
    -- --print native-static-libs 2>&1 | tee "$log"
  local libs
  libs="$(sed -n 's/.*native-static-libs: //p' "$log" | tail -n 1)"
  rm -f "$log"
  if [[ -z "$libs" ]]; then
    echo "rustc did not report native-static-libs for $target" >&2
    exit 1
  fi
  printf '%s\n' "$libs" > "$libs_out"
  [[ -f "target/$target/release/libfushi_p2p.a" ]] || { echo "missing target/$target/release/libfushi_p2p.a" >&2; exit 1; }
}

build_device() {
  local dir="$OUT_DIR/iphoneos"
  mkdir -p "$dir"
  build_target aarch64-apple-ios "$dir/native-static-libs.txt"
  cp "target/aarch64-apple-ios/release/libfushi_p2p.a" "$dir/libfushi_p2p.a"
  lipo -info "$dir/libfushi_p2p.a"
}

build_simulator() {
  local dir="$OUT_DIR/iphonesimulator"
  mkdir -p "$dir"
  build_target aarch64-apple-ios-sim "$dir/.libs.arm64"
  build_target x86_64-apple-ios "$dir/.libs.x86_64"
  lipo -create \
    "target/aarch64-apple-ios-sim/release/libfushi_p2p.a" \
    "target/x86_64-apple-ios/release/libfushi_p2p.a" \
    -output "$dir/libfushi_p2p.a"
  # 两个切片的系统库清单应当一致；直接拼起来——链接器对重复的 -l / -framework 无所谓，
  # 真有差异也不会漏链。
  echo "$(cat "$dir/.libs.arm64") $(cat "$dir/.libs.x86_64")" > "$dir/native-static-libs.txt"
  rm -f "$dir/.libs.arm64" "$dir/.libs.x86_64"
  lipo -info "$dir/libfushi_p2p.a"
}

case "$WHICH" in
  device) build_device ;;
  simulator) build_simulator ;;
  all) build_device; build_simulator ;;
  *) echo "usage: build_ios_staticlib.sh [device|simulator|all]" >&2; exit 2 ;;
esac

# xcconfig 按「磁盘上实际存在的切片」生成，而不是只按本次编的：先编 simulator 再单编
# device 时，两个 SDK 都还能链接。
xc="$OUT_DIR/fushi_p2p.xcconfig"
{
  echo "// Generated by native/fushi_p2p/build_ios_staticlib.sh - do not edit (git-ignored)."
  echo "// Included optionally from fushi/ios/Flutter/{Debug,Release}.xcconfig."
  echo 'FUSHI_P2P_IOS_DIR = $(PROJECT_DIR)/../../native/fushi_p2p/prebuilt/ios'
  for sdk in iphoneos iphonesimulator; do
    [[ -f "$OUT_DIR/$sdk/libfushi_p2p.a" ]] || continue
    echo "FUSHI_P2P_LDFLAGS[sdk=${sdk}*] = -force_load \"\$(FUSHI_P2P_IOS_DIR)/$sdk/libfushi_p2p.a\" $(cat "$OUT_DIR/$sdk/native-static-libs.txt")"
  done
} > "$xc"
echo "==> $xc"
cat "$xc"
